import { notFound } from "next/navigation";

import { Container } from "@/components/Container";
import { getPublicAudit } from "@/services/storage";
import { TOOL_LABELS } from "@/types/tools";

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const audit = getPublicAudit(id);
  if (!audit) return { title: "Audit Not Found" };

  const savings = audit.totals.monthlySavingsUsd;
  const description =
    savings > 0
      ? `This AI stack could save ~$${savings.toLocaleString("en-US")}/mo. See the full breakdown.`
      : "This AI tool stack already looks efficient. See the full audit breakdown.";

  return {
    title: `AI Spend Audit — $${savings.toLocaleString("en-US")}/mo savings`,
    description,
    openGraph: {
      title: "AI Spend Audit Report",
      description,
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: "AI Spend Audit Report",
      description,
    },
  };
}

function formatUsd(n: number): string {
  return n.toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 0 });
}

export default async function AuditPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const audit = getPublicAudit(id);

  if (!audit) notFound();

  return (
    <div className="min-h-screen bg-zinc-50 text-zinc-950 dark:bg-black dark:text-zinc-50">
      <header className="border-b border-zinc-200/60 bg-zinc-50/80 backdrop-blur dark:border-zinc-800/60 dark:bg-black/50">
        <Container>
          <div className="flex h-16 items-center">
            <div className="text-sm font-semibold tracking-tight">AI Spend Audit</div>
          </div>
        </Container>
      </header>

      <main className="py-10">
        <Container>
          <div className="mx-auto max-w-3xl">
            <div className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-950">
              <div className="text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">
                Estimated savings
              </div>
              <div className="mt-2 text-4xl font-bold tracking-tight text-zinc-950 dark:text-zinc-50 md:text-5xl">
                ${formatUsd(audit.totals.monthlySavingsUsd)}/mo
              </div>
              <div className="mt-1 text-lg text-zinc-600 dark:text-zinc-400">
                ~${formatUsd(audit.totals.annualSavingsUsd)}/yr
              </div>

              <div className="mt-2 text-xs text-zinc-500">
                {audit.primaryUseCase} &middot; {audit.teamSize} developer{audit.teamSize !== 1 ? "s" : ""}
              </div>
            </div>

            <div className="mt-6 space-y-3">
              <div className="text-xs font-medium uppercase tracking-wider text-zinc-500 dark:text-zinc-400">
                Per-tool breakdown
              </div>
              {audit.findings.map((f, i) => (
                <div
                  key={i}
                  className="rounded-xl border border-zinc-200 bg-white p-4 shadow-sm dark:border-zinc-800 dark:bg-zinc-950"
                >
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <div className="text-sm font-semibold text-zinc-950 dark:text-zinc-50">
                        {TOOL_LABELS[f.toolId as keyof typeof TOOL_LABELS] ?? f.toolId}
                      </div>
                      <div className="text-xs text-zinc-500">
                        {f.recommendationPlanId}
                      </div>
                    </div>
                    {f.monthlySavingsUsd > 0 ? (
                      <div className="shrink-0 rounded-full bg-emerald-100 px-3 py-1 text-sm font-semibold text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-200">
                        -${formatUsd(f.monthlySavingsUsd)}/mo
                      </div>
                    ) : (
                      <div className="shrink-0 rounded-full bg-zinc-100 px-3 py-1 text-xs text-zinc-500 dark:bg-zinc-800 dark:text-zinc-400">
                        No change
                      </div>
                    )}
                  </div>
                  <p className="mt-2 text-sm leading-6 text-zinc-600 dark:text-zinc-400">{f.reason}</p>
                </div>
              ))}
            </div>

            <div className="mt-8 text-center text-sm text-zinc-500">
              Generated by{" "}
              <a href="/" className="font-medium underline underline-offset-2 hover:text-zinc-700 dark:hover:text-zinc-300">
                AI Spend Audit
              </a>
            </div>
          </div>
        </Container>
      </main>
    </div>
  );
}
